### ISSUE TITLE
项目为啥没用 TS 写服务端，而用了 JS

### ISSUE THREAD

**Issue by zoujiaqing** [hezhongfeng/im-server#34]

**Comment by hezhongfeng** [comment]
有什么区别吗？再说这都是多少年前的了，现在用 nestjs 的话，肯定是 ts 了，不过和 js 区别不大，无所谓的

**Comment by zoujiaqing** [comment]
客户端用 js 和 ts 问题不大，但是服务端问题差很多，强类型和弱类型问题，毕竟要落地到数据库，不能啥错误都让数据库往出抛。
